# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/versa/ECE385/ip_repo/hdmi_text_controller_1_0/src/Pawn_rom/Pawn_rom.xci
# IP: The module: 'Pawn_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/versa/ECE385/ip_repo/hdmi_text_controller_1_0/src/Pawn_rom/Pawn_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Pawn_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/versa/ECE385/ip_repo/hdmi_text_controller_1_0/src/Pawn_rom/Pawn_rom.xci
# IP: The module: 'Pawn_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/versa/ECE385/ip_repo/hdmi_text_controller_1_0/src/Pawn_rom/Pawn_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Pawn_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
