# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/versa/ECE385/FinalProject/FinalProject.srcs/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/mb_usb_hdmi_text_controller_0_0.xci
# IP: The module: 'mb_usb_hdmi_text_controller_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/src/Bishop_rom/Bishop_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Bishop_rom || ORIG_REF_NAME==Bishop_rom} -quiet] -quiet

# IP: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/src/King_rom/King_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==King_rom || ORIG_REF_NAME==King_rom} -quiet] -quiet

# IP: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/src/Knight_rom/Knight_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Knight_rom || ORIG_REF_NAME==Knight_rom} -quiet] -quiet

# IP: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/src/Pawn_rom/Pawn_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pawn_rom || ORIG_REF_NAME==Pawn_rom} -quiet] -quiet

# IP: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/src/Queen_rom/Queen_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Queen_rom || ORIG_REF_NAME==Queen_rom} -quiet] -quiet

# IP: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/src/Rook_rom/Rook_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Rook_rom || ORIG_REF_NAME==Rook_rom} -quiet] -quiet

# IP: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/src/chessBoard_rom_1/chessBoard_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chessBoard_rom || ORIG_REF_NAME==chessBoard_rom} -quiet] -quiet

# IP: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/src/hdmi_tx_0/hdmi_tx_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_tx_0 || ORIG_REF_NAME==hdmi_tx_0} -quiet] -quiet

# IP: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/src/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# IP: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/src/blk_mem_gen_0/blk_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/src/Bishop_rom/Bishop_rom_ooc.xdc

# XDC: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/src/King_rom/King_rom_ooc.xdc

# XDC: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/src/Knight_rom/Knight_rom_ooc.xdc

# XDC: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/src/Pawn_rom/Pawn_rom_ooc.xdc

# XDC: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/src/Queen_rom/Queen_rom_ooc.xdc

# XDC: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/src/Rook_rom/Rook_rom_ooc.xdc

# XDC: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/src/chessBoard_rom_1/chessBoard_rom_ooc.xdc

# XDC: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/src/clk_wiz_0/clk_wiz_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/src/clk_wiz_0/clk_wiz_0_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/src/clk_wiz_0/clk_wiz_0_ooc.xdc

# XDC: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# IP: C:/Users/versa/ECE385/FinalProject/FinalProject.srcs/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/mb_usb_hdmi_text_controller_0_0.xci
# IP: The module: 'mb_usb_hdmi_text_controller_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/src/Bishop_rom/Bishop_rom.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Bishop_rom || ORIG_REF_NAME==Bishop_rom} -quiet] -quiet

# IP: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/src/King_rom/King_rom.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==King_rom || ORIG_REF_NAME==King_rom} -quiet] -quiet

# IP: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/src/Knight_rom/Knight_rom.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Knight_rom || ORIG_REF_NAME==Knight_rom} -quiet] -quiet

# IP: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/src/Pawn_rom/Pawn_rom.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Pawn_rom || ORIG_REF_NAME==Pawn_rom} -quiet] -quiet

# IP: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/src/Queen_rom/Queen_rom.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Queen_rom || ORIG_REF_NAME==Queen_rom} -quiet] -quiet

# IP: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/src/Rook_rom/Rook_rom.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Rook_rom || ORIG_REF_NAME==Rook_rom} -quiet] -quiet

# IP: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/src/chessBoard_rom_1/chessBoard_rom.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chessBoard_rom || ORIG_REF_NAME==chessBoard_rom} -quiet] -quiet

# IP: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/src/hdmi_tx_0/hdmi_tx_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_tx_0 || ORIG_REF_NAME==hdmi_tx_0} -quiet] -quiet

# IP: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/src/clk_wiz_0/clk_wiz_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# IP: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/src/blk_mem_gen_0/blk_mem_gen_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/src/Bishop_rom/Bishop_rom_ooc.xdc

# XDC: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/src/King_rom/King_rom_ooc.xdc

# XDC: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/src/Knight_rom/Knight_rom_ooc.xdc

# XDC: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/src/Pawn_rom/Pawn_rom_ooc.xdc

# XDC: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/src/Queen_rom/Queen_rom_ooc.xdc

# XDC: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/src/Rook_rom/Rook_rom_ooc.xdc

# XDC: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/src/chessBoard_rom_1/chessBoard_rom_ooc.xdc

# XDC: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/src/clk_wiz_0/clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/src/clk_wiz_0/clk_wiz_0_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/src/clk_wiz_0/clk_wiz_0_ooc.xdc

# XDC: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
