# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/versa/Downloads/lab7_1_provided_fa24/mb_usb_hdmi_top.xdc

# Block Designs: bd/mb_usb/mb_usb.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb || ORIG_REF_NAME==mb_usb} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_xbar_0/mb_usb_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_xbar_0 || ORIG_REF_NAME==mb_usb_xbar_0} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_microblaze_0_axi_periph_1/mb_usb_microblaze_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_microblaze_0_axi_periph_1 || ORIG_REF_NAME==mb_usb_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_microblaze_0_axi_intc_1/mb_usb_microblaze_0_axi_intc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_microblaze_0_axi_intc_1 || ORIG_REF_NAME==mb_usb_microblaze_0_axi_intc_1} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_mdm_1_0/mb_usb_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_mdm_1_0 || ORIG_REF_NAME==mb_usb_mdm_1_0} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_clk_wiz_1_0/mb_usb_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_clk_wiz_1_0 || ORIG_REF_NAME==mb_usb_clk_wiz_1_0} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_rst_clk_wiz_1_100M_0/mb_usb_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mb_usb_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_axi_uartlite_0_0/mb_usb_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_axi_uartlite_0_0 || ORIG_REF_NAME==mb_usb_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_microblaze_0_2/mb_usb_microblaze_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_microblaze_0_2 || ORIG_REF_NAME==mb_usb_microblaze_0_2} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_dlmb_v10_2/mb_usb_dlmb_v10_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_dlmb_v10_2 || ORIG_REF_NAME==mb_usb_dlmb_v10_2} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_ilmb_v10_2/mb_usb_ilmb_v10_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_ilmb_v10_2 || ORIG_REF_NAME==mb_usb_ilmb_v10_2} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_dlmb_bram_if_cntlr_2/mb_usb_dlmb_bram_if_cntlr_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_dlmb_bram_if_cntlr_2 || ORIG_REF_NAME==mb_usb_dlmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_ilmb_bram_if_cntlr_2/mb_usb_ilmb_bram_if_cntlr_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_ilmb_bram_if_cntlr_2 || ORIG_REF_NAME==mb_usb_ilmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_lmb_bram_2/mb_usb_lmb_bram_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_lmb_bram_2 || ORIG_REF_NAME==mb_usb_lmb_bram_2} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_microblaze_0_xlconcat_0/mb_usb_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_microblaze_0_xlconcat_0 || ORIG_REF_NAME==mb_usb_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_axi_gpio_0_0/mb_usb_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_axi_gpio_0_0 || ORIG_REF_NAME==mb_usb_axi_gpio_0_0} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_axi_gpio_0_1/mb_usb_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_axi_gpio_0_1 || ORIG_REF_NAME==mb_usb_axi_gpio_0_1} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_axi_gpio_0_2/mb_usb_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_axi_gpio_0_2 || ORIG_REF_NAME==mb_usb_axi_gpio_0_2} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_axi_timer_0_0/mb_usb_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_axi_timer_0_0 || ORIG_REF_NAME==mb_usb_axi_timer_0_0} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_axi_quad_spi_0_0/mb_usb_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_axi_quad_spi_0_0 || ORIG_REF_NAME==mb_usb_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_hdmi_text_controller_0_0/mb_usb_hdmi_text_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_hdmi_text_controller_0_0 || ORIG_REF_NAME==mb_usb_hdmi_text_controller_0_0} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_axi_gpio_0_4/mb_usb_axi_gpio_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_axi_gpio_0_4 || ORIG_REF_NAME==mb_usb_axi_gpio_0_4} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_axi_gpio_0_5/mb_usb_axi_gpio_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_axi_gpio_0_5 || ORIG_REF_NAME==mb_usb_axi_gpio_0_5} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_axi_gpio_0_6/mb_usb_axi_gpio_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_axi_gpio_0_6 || ORIG_REF_NAME==mb_usb_axi_gpio_0_6} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_axi_gpio_1_0/mb_usb_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_axi_gpio_1_0 || ORIG_REF_NAME==mb_usb_axi_gpio_1_0} -quiet] -quiet

# XDC: c:/Users/versa/ECE385/FinalProject/lab7_1_new.gen/sources_1/bd/mb_usb/mb_usb_ooc.xdc
